### ISSUE TITLE
build error handling for collector

### ISSUE THREAD

**Issue by sidetrackedmind** [codeforpdx/opentransit-collector#11]
## Issue
Last week, when the streetcar provider got an error it blocked the other provider, trimet, from getting data and putting it in s3. 

## Proposed fix
I propose two improvements:
1. better error handling / logging in the nextbus provider script
2. separating the provider calls so that they can fail independently 

### 1. better error handling / logging in the nextbus provider script
See code here for Portland's streetcar provider nextbus - https://github.com/codeforpdx/opentransit-collector/blob/master/src/providers/nextbus.js. We could build in some error handling to try/except flow and log errors. Logging errors would be helpful to aid in bug fixing. Right now, the errors go to the console. If you miss it, it can be hard to recreate.

### 2. separating the provider calls so that they can fail independently 
We could add better error handling to the index.js file https://github.com/codeforpdx/opentransit-collector/blob/master/src/index.js. When the streetcar (nextbus) provider was broken, it was blocking the trimet gtfs-realtime collector from working. Ideally, each provider could fail independently.

**Comment by sidetrackedmind** [comment]
The error message was this:
```
collector-dev    | { Error: connect ECONNREFUSED 44.236.119.121:443
collector-dev    |     at Object._errnoException (util.js:1019:11)
collector-dev    |     at _exceptionWithHostPort (util.js:1041:20)
collector-dev    |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
collector-dev    |   code: 'ECONNREFUSED',
collector-dev    |   errno: 'ECONNREFUSED',
collector-dev    |   syscall: 'connect',
collector-dev    |   address: '44.236.119.121',
collector-dev    |   port: 443,
collector-dev    |   config:
collector-dev    |    { adapter: [Function: httpAdapter],
collector-dev    |      transformRequest: { '0': [Function: transformRequest] },
collector-dev    |      transformResponse: { '0': [Function: transformResponse] },
collector-dev    |      timeout: 0,
collector-dev    |      xsrfCookieName: 'XSRF-TOKEN',
collector-dev    |      xsrfHeaderName: 'X-XSRF-TOKEN',
collector-dev    |      maxContentLength: -1,
collector-dev    |      validateStatus: [Function: validateStatus],
collector-dev    |      headers:
collector-dev    |       { Accept: 'application/json, text/plain, */*',
collector-dev    |         'User-Agent': 'axios/0.16.2' },
collector-dev    |      method: 'get',
collector-dev    |      url: 'https://retro.umoiq.com/service/publicJSONFeed?command=vehicleLocations&t=0&a=portland-sc',
collector-dev    |      data: undefined },
collector-dev    |   request:
collector-dev    |    Writable {
collector-dev    |      _writableState:
collector-dev    |       WritableState {
collector-dev    |         objectMode: false,
collector-dev    |         highWaterMark: 16384,
collector-dev    |         finalCalled: false,
collector-dev    |         needDrain: false,
collector-dev    |         ending: false,
collector-dev    |         ended: false,
collector-dev    |         finished: false,
collector-dev    |         destroyed: false,
collector-dev    |         decodeStrings: true,
collector-dev    |         defaultEncoding: 'utf8',
collector-dev    |         length: 0,
collector-dev    |         writing: false,
collector-dev    |         corked: 0,
collector-dev    |         sync: true,
collector-dev    |         bufferProcessing: false,
collector-dev    |         onwrite: [Function: bound onwrite],
collector-dev    |         writecb: null,
collector-dev    |         writelen: 0,
collector-dev    |         bufferedRequest: null,
collector-dev    |         lastBufferedRequest: null,
collector-dev    |         pendingcb: 0,
collector-dev    |         prefinished: false,
collector-dev    |         errorEmitted: false,
collector-dev    |         bufferedRequestCount: 0,
collector-dev    |         corkedRequestsFree: [Object] },
collector-dev    |      writable: true,
collector-dev    |      domain: null,
collector-dev    |      _events:
collector-dev    |       { response: [Function: handleResponse],
collector-dev    |         error: [Function: handleRequestError] },
collector-dev    |      _eventsCount: 2,
collector-dev    |      _maxListeners: undefined,
collector-dev    |      _options:
collector-dev    |       { maxRedirects: 21,
collector-dev    |         protocol: 'https:',
collector-dev    |         hostname: 'retro.umoiq.com',
collector-dev    |         port: null,
collector-dev    |         path: '/service/publicJSONFeed?command=vehicleLocations&t=0&a=portland-sc',
collector-dev    |         method: 'get',
collector-dev    |         headers: [Object],
collector-dev    |         agent: undefined,
collector-dev    |         auth: undefined,
collector-dev    |         pathname: '/service/publicJSONFeed',
collector-dev    |         search: '?command=vehicleLocations&t=0&a=portland-sc' },
collector-dev    |      _redirectCount: 0,
collector-dev    |      _bufferedWrites: [],
collector-dev    |      _onNativeResponse: [Function],
collector-dev    |      _currentRequest:
collector-dev    |       ClientRequest {
collector-dev    |         domain: null,
collector-dev    |         _events: [Object],
collector-dev    |         _eventsCount: 5,
collector-dev    |         _maxListeners: undefined,
collector-dev    |         output: [],
collector-dev    |         outputEncodings: [],
collector-dev    |         outputCallbacks: [],
collector-dev    |         outputSize: 0,
collector-dev    |         writable: true,
collector-dev    |         _last: true,
collector-dev    |         upgrading: false,
collector-dev    |         chunkedEncoding: false,
collector-dev    |         shouldKeepAlive: false,
collector-dev    |         useChunkedEncodingByDefault: false,
collector-dev    |         sendDate: false,
collector-dev    |         _removedConnection: false,
collector-dev    |         _removedContLen: false,
collector-dev    |         _removedTE: false,
collector-dev    |         _contentLength: 0,
collector-dev    |         _hasBody: true,
collector-dev    |         _trailer: '',
collector-dev    |         finished: true,
collector-dev    |         _headerSent: true,
collector-dev    |         socket: [Object],
collector-dev    |         connection: [Object],
collector-dev    |         _header: 'GET /service/publicJSONFeed?command=vehicleLocations&t=0&a=portland-sc HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.16.2\r\nHost: retro.umoiq.com\r\nConnection: close\r\n\r\n',
collector-dev    |         _onPendingData: [Function: noopPendingOutput],
collector-dev    |         agent: [Object],
collector-dev    |         socketPath: undefined,
collector-dev    |         timeout: undefined,
collector-dev    |         method: 'GET',
collector-dev    |         path: '/service/publicJSONFeed?command=vehicleLocations&t=0&a=portland-sc',
collector-dev    |         _ended: false,
collector-dev    |         res: null,
collector-dev    |         aborted: undefined,
collector-dev    |         timeoutCb: null,
collector-dev    |         upgradeOrConnect: false,
collector-dev    |         parser: null,
collector-dev    |         maxHeadersCount: null,
collector-dev    |         _redirectable: [Circular],
collector-dev    |         [Symbol(outHeadersKey)]: [Object] },
collector-dev    |      _currentUrl: 'https://retro.umoiq.com/service/publicJSONFeed?command=vehicleLocations&t=0&a=portland-sc' },
collector-dev    |   response: undefined }
```

**Comment by liamphmurphy** [comment]
Did a bit of looking into this. My guess is the root cause of one provider failing breaking the other is due to this line: https://github.com/codeforpdx/opentransit-collector/blob/d576f0caf5bff3b23938b5d9660de0aaf50c3315/src/index.js#L81

Not a JS wizard but after some looking, looks like it is used for asynchronous calls and ensures that all of the promises executed successfully. If one promises fails, then execution of any of the promises won't continue. The naive answer would be to remove that line. But I'll do some digging to look at any consequences of that.

Since these "promises" (one promise for each provider) don't rely on each other and don't communicate with each other in anyway, my hunch is we don't need it.
